### ISSUE TITLE
Check Fair Data Economy "Dataset Terms of Use [Template]" requirements for data products

### ISSUE THREAD

**Issue by kyyberi** [Open-Data-Product-Initiative/open-data-product-spec-1.1dev#12]
**Idea Description**
The rulebook for a fair data economy is a guide for creators of fair data economy networks. Agreement templates and other tools make it easier to build and join new data networks which highlight transparency in data sharing.

Review the rule book for the dataset terms of use and find out which parts are already covered by the open data product spec and which are not. Document all the findings. Based on this work we can design needed changes to the Open Data Product Specification. See attached Rule book. 
[rulebook-for-a-fair-data-economy-part-2.pdf](https://github.com/Open-Data-Product-Initiative/open-data-product-spec-1.1dev/files/9793651/rulebook-for-a-fair-data-economy-part-2.pdf)

More information about the rule book from here https://www.sitra.fi/en/publications/rulebook-for-a-fair-data-economy/#preface-and-templates

**Comment by kyyberi** [comment]
Create a subgroup to work with this? It's likely that this takes time and external people from 1000 Lakes is somehow involved.

**Comment by kyyberi** [comment]
In the same process create joint marketing material. It sounds more and more like a good reason to create a subgroup.

**Comment by kyyberi** [comment]
Joint group with Rulebook team and ODPI team will be established soon.

**Comment by niilahti** [comment]
TSC 15.11.2022: A decision has been made about establishing the group. The group will make following decisions.
