### ISSUE TITLE
Internal data product description

### ISSUE THREAD

**Issue by niilahti** [Open-Data-Product-Initiative/open-data-product-spec-1.1dev#23]
Based on feedback and discussion:

When data product is internal:

Document level attributes:
`onlyInternal boolean`
Data Holder:
`internalBU (business unit) string`

Research and discussion are still needed for the solution proposal.

**Comment by kyyberi** [comment]
I disagree about the need for yet another attribute to indicate private usage. There is already 

**visibility**: REQUIRED The publicity level eg who can see this product. Private - just the creator. Organisation - visible to all in your organisation. Public - visible to all publicly. 

If you use data product internal only, then select organisation. That is internal use.

**Comment by niilahti** [comment]
Thank you for clarification. Agreed,  I forgot this option.
