### ISSUE TITLE
Product management: Data product portfolio, product line, product series etc. 

### ISSUE THREAD

**Issue by niilahti** [Open-Data-Product-Initiative/open-data-product-spec-1.1dev#38]
Data product document level attribute contains information about the product portfolio, family, line, series etc. to which it belongs.

This requires a discussion, especially from a product management perspective.

**Comment by niilahti** [comment]
Document level attributes / optional attributes

**Comment by kyyberi** [comment]
One clear addition would be to add "group" attribute. In that use can name Data product portfolio, product line, product series

**Comment by niilahti** [comment]
Some n level product mgmt category would be good to have

**Comment by niilahti** [comment]
This is important when bundling DPs, for example

**Comment by niilahti** [comment]
Also dependencies needs to defined, for example non-individual product

**Comment by niilahti** [comment]
Pull request + merge
