### ISSUE TITLE
Combine specsURL and documentationURL

### ISSUE THREAD

**Issue by niilahti** [Open-Data-Product-Initiative/open-data-product-spec-1.1dev#4]
Should we compine specsURL and documentationURL?  I think, only e.g. docURL should be enough.

**Comment by kyyberi** [comment]
I would reconsider. When I added those in the initial spec the difference was clear in my head. specsURL is the machine-readable file. The documentation refers to guides and alike documentation which show how data product is taken into use, used in common use cases and so on. That said, one option is to rename documentationURL to guideURL or alike.

**Comment by niilahti** [comment]
Good point! This should work then:

```
  "specsURL": "http://192.168.10.1/petshop.json",
    "documentationURL": "http://192.168.10.1/petshop"
```

**Comment by niilahti** [comment]
specsURL:

The URL of the data access documentation, preferably in a machine-readable format, such as OpenAPI specs.

**Comment by niilahti** [comment]
documentationURL:

The URL of the data access documentation or guide.
