### ISSUE TITLE
Add related use cases to the model

### ISSUE THREAD

**Issue by kyyberi** [Open-Data-Product-Initiative/open-data-product-spec-1.1dev#43]
**Idea Description**
Data products are created for a purpose. More often there is a clear usecase (or multiple) in which this particular data product can provide value. Associate the usecase descriptions and data product. 

It could be list of items:

- Name of the use case
- Link to the description

**Comment by niilahti** [comment]
Behind the link there could be machine readable use case description, such as json, xml

**Comment by niilahti** [comment]
Simular idea as DataOps Yaml file

**Comment by kyyberi** [comment]
Done
